AYS-65 | GetAdminRegistrationApplicationIdSummaryTest.java test cases added.
afet-yonetim-sistemi/ays-be-api-automation pull request #123
Opened 2024-01-08 19:39 UTC by cagla88

This PR about api/v1/admin/registration-application/{id}/summary endpoint.
Positive and negative test cases added.

2024-01-08 20:07 UTC, agitrubard requested changes
Selamlar @cagla88,
Commit history'sinde bir farklılık tespit ettim, acaba branch açma sürecinde bir farklılık mı vardı diye süreci özetliyorum;

- `main` branch'e geçilir
- sonrasında update alınır yani branch güncellenir, son commitler alınır
- bu branch üzerinden yeni bir branch açılır ve değişiklikler bu branchte yapılarak commitlenerek pushlanır

Bu adımları uyguladığımız durumda 20 tane commit görünmüyor olması gerekiyor.

2024-01-08 20:33 UTC, cagla88 commented
@agitrubard dediğiniz gibi yapıyorum her intellij i açtığımda ilk işim maini güncelliyorum daha sonra çalışacagım branch i açıp merge into yapıp o şekilde geliştirmeye devam ediyorum. Neden böyle görünüyor bilmiyorum sanırım birden fazla branch te aynı anda çalıştığım için oluyor olabilir branchler arası geçiş yapıyorum diye midir?

2024-01-08 22:15 UTC, Nbhtozcn commented
Ben branchlesr arasında calistigimda boyle bir durum yaşamadım

2024-01-08 22:16 UTC, Nbhtozcn approved these changes

2024-01-09 10:58 UTC, agitrubard commented
> @agitrubard dediğiniz gibi yapıyorum her intellij i açtığımda ilk işim maini güncelliyorum daha sonra çalışacagım branch i açıp merge into yapıp o şekilde geliştirmeye devam ediyorum. Neden böyle görünüyor bilmiyorum sanırım birden fazla branch te aynı anda çalıştığım için oluyor olabilir branchler arası geçiş yapıyorum diye midir?

@cagla88 3. maddede yazdığım yeni branch açma kısmını yapmıyorsunuz gibi anladım. Merge into yapmaya ihtiyaç kalmıyor bu sebeple oradaki maddelere de eklememişim. Aslında sadece main üzerinden yeni bir branch açmak yetiyor. Her merge yapıldığında yepyeni bir merge commit ekleniyor. Bu commit ile birlikte farklılık oluşuyor. Git ile ilgili https://aliozgur.gitbooks.io/git101/content/index.html bu dokümanı önerebilirim, bir çok şeyi netleştirecektir ✅

2024-01-09 11:27 UTC, agitrubard approved these changes

2024-01-09 11:27 UTC, merged