AYS-152 | The Auth package has been rearranged according to endpoints.
afet-yonetim-sistemi/ays-be-api-automation pull request #138
Opened 2024-02-22 15:32 UTC by cagla88

Auth tests package kullanıcı ve endpoint adına göre ayrı classlara ayrıldı.
Eski classlar xml dosyalarından kaldırıldı.
Yeni oluşturulanlar AYS-148 issues'u ile runner classlara eklenecektir.
Testlerin çalışırlığı kontrol edildi.

2024-02-22 15:46 UTC, cagla88 commented on src/test/java/org/ays/tests/auth/institutionAuthServiseTests/GetAdminTokenTest.java
> +    }
tmmdır hepsini değiştiririm 👍🏻

2024-02-22 17:47 UTC, agitrubard commented on src/test/java/org/ays/tests/auth/institutionAuthServiseTests/GetAdminTokenTest.java
> +    }
Hepsini değiştirmeyebiliriz, sadece burası için bir avantaj sağlamıyor

2024-02-23 17:10 UTC, cagla88 commented on src/test/java/org/ays/tests/auth/institutionAuthServiseTests/GetAdminTokenTest.java
> +    }
güncelledim kontrol edip mergeleyebilir misiniz

2024-02-24 11:07 UTC, agitrubard requested changes

2024-02-24 11:07 UTC, agitrubard commented on src/test/java/org/ays/tests/auth/institutionAuthServiseTests/GetAdminTokenTest.java
>      AdminCredentials adminCredentials;
Değişkeni kullandığımız yerde tanımlamamız daha doğru bir yaklaşım olur

2024-02-24 11:07 UTC, agitrubard commented on src/test/java/org/ays/tests/auth/userAuthServiceTests/PostUserInvalidateTokenTest.java
>      UserCredentials userCredentials;
Değişkeni kullandığımız yerde tanımlamamız daha doğru bir yaklaşım olur

2024-02-25 09:07 UTC, cagla88 commented on src/test/java/org/ays/tests/auth/institutionAuthServiseTests/GetAdminTokenTest.java
>      AdminCredentials adminCredentials;
Gerekli değişikliği sağladım.

2024-02-25 09:07 UTC, cagla88 commented on src/test/java/org/ays/tests/auth/userAuthServiceTests/PostUserInvalidateTokenTest.java
>      UserCredentials userCredentials;
Gerekli değişikliği sağladım.

2024-02-25 13:52 UTC, agitrubard requested changes

2024-02-25 13:52 UTC, agitrubard commented on src/test/java/org/ays/tests/auth/institutionAuthServiseTests/GetAdminTokenTest.java
>          adminCredentials = Helper.setIntsAdminCredentials();
```suggestion
        AdminCredentials adminCredentials = Helper.setIntsAdminCredentials();
```

2024-02-25 13:52 UTC, agitrubard commented on src/test/java/org/ays/tests/auth/userAuthServiceTests/PostUserInvalidateTokenTest.java
>          userCredentials = Helper.createNewUser();
```suggestion
        UserCredentials userCredentials = Helper.createNewUser();
```

2024-02-25 17:37 UTC, cagla88 commented on src/test/java/org/ays/tests/auth/userAuthServiceTests/PostUserInvalidateTokenTest.java
>          userCredentials = Helper.createNewUser();
Tamamlandı..

2024-02-26 16:10 UTC, merged