AYS-186 | `PostAdminRegistrationApplicationIDCompleteTest` added.
afet-yonetim-sistemi/ays-be-api-automation pull request #146
Opened 2024-03-16 14:02 UTC by cagla88

- `PostAdminRegistrationApplicationIDCompleteTest` class oluşturuldu.
- `COMPLETED` statüsüne sahip applicationID bilgisi için `InstitutionEndpoints` içerisine method oluşturuldu.
- `Filter` class a `generate` methodu eklendi.
- `ApplicationRegistrationSupportStatus` enum payload packgace altına eklendi.
- `RequestBodyInstitution` classına `generateFilter` methodu eklendi.
- `AysRandomUtil` classına `generateUsername, generateEmailAddress, generatePassword` methodları eklendi.
- `DataProvider` classına` invalidFirstAndLastNamesDataForAdminRegistration, invalidEmailForAdminRegistration, invalidPhoneNumberDataForRegistrationComplete` methodları eklendi.

2024-03-16 15:46 UTC, agitrubard requested changes

2024-03-16 15:46 UTC, agitrubard commented on src/test/java/org/ays/endpoints/InstitutionEndpoints.java
> +import org.ays.payload.*;
https://www.baeldung.com/intellij-disable-wildcard-import
```suggestion
import org.ays.payload.AdminsListPayload;
import org.ays.payload.ApplicationRegistration;
import org.ays.payload.Assignment;
import org.ays.payload.RejectReason;
import org.ays.payload.RequestBodyAssignments;
import org.ays.payload.RequestBodyInstitution;
import org.ays.payload.RequestBodyUsers;
import org.ays.payload.User;
import org.ays.payload.UserCredentials;
```

2024-03-16 15:46 UTC, agitrubard commented on src/test/java/org/ays/payload/RequestBodyForRegistrationIDComplete.java
> +    public static RequestBodyForRegistrationIDComplete generateRequestBody() {
```suggestion
    public static RegistrationApplicationCompletePayload generate() {
```

2024-03-16 15:46 UTC, agitrubard commented on src/test/java/org/ays/payload/RequestBodyForRegistrationIDComplete.java
> +public class RequestBodyForRegistrationIDComplete {
```suggestion
public class RegistrationApplicationCompletePayload {
```

2024-03-16 15:46 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
> +    RequestBodyForRegistrationIDComplete registrationIDComplete;
```suggestion
```
Bu alanları kaldırıp, metotların içerisinde tanımlayalım

2024-03-16 20:31 UTC, cagla88 commented
@agitrubard istenilen değişiklikleri yapıp gönderdim

2024-03-17 09:29 UTC, agitrubard requested changes

2024-03-17 09:29 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
> +        RegistrationApplicationCompletePayload registrationIDComplete = RegistrationApplicationCompletePayload.generate();
```suggestion
        RegistrationApplicationCompletePayload completePayload = RegistrationApplicationCompletePayload.generate();
```

2024-03-17 09:29 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
> +        RegistrationApplicationCompletePayload registrationIDComplete = RegistrationApplicationCompletePayload.generate();
```suggestion
        RegistrationApplicationCompletePayload completePayload = RegistrationApplicationCompletePayload.generate();
```

2024-03-17 09:29 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
> +        RegistrationApplicationCompletePayload registrationIDComplete = RegistrationApplicationCompletePayload.generate();
```suggestion
        RegistrationApplicationCompletePayload completePayload = RegistrationApplicationCompletePayload.generate();
```

2024-03-17 09:29 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
> +        RegistrationApplicationCompletePayload registrationIDComplete = RegistrationApplicationCompletePayload.generate();
```suggestion
        RegistrationApplicationCompletePayload completePayload = RegistrationApplicationCompletePayload.generate();
```

2024-03-17 09:29 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
> +        RegistrationApplicationCompletePayload registrationIDComplete = RegistrationApplicationCompletePayload.generate();
```suggestion
        RegistrationApplicationCompletePayload completePayload = RegistrationApplicationCompletePayload.generate();
```

2024-03-17 09:29 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
> +        RegistrationApplicationCompletePayload registrationIDComplete = RegistrationApplicationCompletePayload.generate();
```suggestion
        RegistrationApplicationCompletePayload completePayload = RegistrationApplicationCompletePayload.generate();
```

2024-03-17 09:29 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
> +        RegistrationApplicationCompletePayload registrationIDComplete = RegistrationApplicationCompletePayload.generate();
```suggestion
        RegistrationApplicationCompletePayload completePayload = RegistrationApplicationCompletePayload.generate();
```

2024-03-17 09:39 UTC, agitrubard approved these changes

2024-03-17 09:46 UTC, merged