AYS-193 | Added positive scenarios for application
afet-yonetim-sistemi/ays-be-api-automation pull request #148
Opened 2024-04-18 02:43 UTC by Nbhtozcn

approval and rejection endpoints.

## Pull Request

**Description:**
Provide a brief description of the changes in this pull request.

**Related Issue:**
Closes #[AYS-193]

**Changes Made:**

- Added positive scenarios for application rejection and approval.

- Removed HttpStatus from specifications and assertions.

- Deleted location and assignment-related code.

- Enabled previously failed test cases for future updates and raised corresponding Jira issues

- Applied AysResponseSpec classes to several classes.

**Additional Information:**
Add any additional information that might be relevant to reviewers.

## Checklist
- [x] I have read and followed the [contribution guidelines](README.md#contributing) for this project.
- [x] I have added tests (if applicable).
- [x] All tests are passing.
- [x] I have updated the documentation (if necessary).

## Reviewer Instructions
Provide instructions or guidelines for reviewers to follow when assessing your pull request.

2024-04-18 06:41 UTC, agitrubard requested changes

2024-04-18 06:41 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationRejectTest.java
> +                .body("response.status", equalTo("REJECTED"));
`"REJECTED"` yerine enum objeler oluşturularak kullanılabilir

2024-04-18 06:42 UTC, agitrubard commented
@Nbhtozcn branch isimlerinde `|` yerine `/` kullanabiliriz

2024-04-19 10:15 UTC, agitrubard requested changes

2024-04-19 10:15 UTC, agitrubard commented on src/test/java/org/ays/payload/ApplicationStatus.java
> +public enum ApplicationStatus {
Aşağıdaki şekilde güncellememiz daha iyi olur, ilerleyen dönemde başka başvuru aşamaları da olacak, karışabilir
```suggestion
public enum AdminUserRegisterationApplicationStatus {
```

2024-04-20 03:26 UTC, Nbhtozcn commented on src/test/java/org/ays/payload/ApplicationStatus.java
> +public enum ApplicationStatus {
Haklisin @agitrubard. Değiştirip yolluyorum.

2024-04-20 12:54 UTC, agitrubard approved these changes

2024-04-20 17:22 UTC, merged