AYS-221| Added Emergency Evacuation Application automation tests
afet-yonetim-sistemi/ays-be-api-automation pull request #152
Opened 2024-06-26 18:03 UTC by Nbhtozcn

## Pull Request

**Description:**
Added Emergency Evacuation Application automation tests

**Related Issue:**
Closes #[221]

**Changes Made:**

- LandingEndpoints Class Added

- Enum Class Added for Error Messages

- Post Emergency Evacuation Application Classes Added for api/v1/emergency-evacuation-application Endpoint

**Additional Information:**
Add any additional information that might be relevant to reviewers.

## Checklist
- [x] I have read and followed the [contribution guidelines](README.md#contributing) for this project.
- [x] I have added tests (if applicable).
- [x] All tests are passing.
- [x] I have updated the documentation (if necessary).

## Reviewer Instructions
Provide instructions or guidelines for reviewers to follow when assessing your pull request.

2024-06-27 08:19 UTC, cagla88 requested changes

2024-06-28 01:34 UTC, Nbhtozcn commented on src/test/java/org/ays/utility/AysRandomUtil.java
> +
Selam @cagla88 , dikkat etmemişim. Degistirdim 👍🏻

2024-06-28 11:23 UTC, cagla88 approved these changes

2024-06-28 14:16 UTC, merged

2024-06-29 10:13 UTC, agitrubard commented
@Nbhtozcn mergeledikten sonra branch'i silebilir miyiz?