AYS-317 | User Listing Service
afet-yonetim-sistemi/ays-be-api-automation pull request #154
Opened 2024-07-13 19:26 UTC by cagla88

…ring

## Pull Request

**Description:**
Filtreleme olmadan Kuruma kayıtlı kullanıcıların listelenmesi için pozitif testler eklendi

**Related Issue:**
Closes #[AYS-317]

**Changes Made:**
AYS, Disaster Foundation ve Volunteer Foundation için ayrı ayrı testler yapıldı.
Her bir yöneticiye bağlı kullanıcı sayısı için veri tabanındaki verilerle örtüştüğü test edildi.
Github Action için environment variable eklendi.

## Checklist
- [x] I have read and followed the [contribution guidelines](README.md#contributing) for this project.
- [x] I have added tests (if applicable).
- [x] All tests are passing.
- [x] I have updated the documentation (if necessary).

2024-07-17 19:25 UTC, agitrubard requested changes

2024-07-17 19:25 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/usermanagementservice/PostUsersTest.java
> +        }
```suggestion
        if (contentList == null || contentList.isEmpty()) {
            AysLogUtil.info("No users under this institution.");
            return;
        }
        
        response.then()
                .spec(AysResponseSpecs.expectBadRequestResponseSpec())
                .spec(AysResponseSpecs.subErrorsSpec(errorMessage, field, type));
```

2024-07-17 19:25 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/usermanagementservice/PostUsersTest.java
> +        }
```suggestion
        if (contentList == null || contentList.isEmpty()) {
            AysLogUtil.info("No users under this institution.");
            return;
        }
        
        response.then()
                .spec(AysResponseSpecs.expectBadRequestResponseSpec())
                .spec(AysResponseSpecs.subErrorsSpec(errorMessage, field, type));
```

2024-07-17 19:25 UTC, agitrubard commented on src/test/java/org/ays/tests/institution/usermanagementservice/PostUsersTest.java
> +        }
```suggestion

        if (response.jsonPath().getList("response.content").isEmpty()) {
            AysLogUtil.info("No users under this institution.");
            return;
        }
        
        response.then()
                .spec(AysResponseSpecs.expectSuccessResponseSpec())
                .spec(AysResponseSpecs.expectUserDetailsInContent());
        
```

2024-07-17 19:59 UTC, agitrubard approved these changes

2024-07-18 00:34 UTC, Nbhtozcn commented on src/test/java/org/ays/utility/AysResponseSpecs.java
> +        VolunteerFoundation.tearDown();
Bu ve devamındaki diğer iki Response Specification icin bu kisimlarin test içerisinde yapılıp sadece tek bir 
```
public static ResponseSpecification expectTotalElementCount() {
        return new ResponseSpecBuilder()
                .expectBody("response.totalElementCount", equalTo(totalElementCount))
                .build();

    }
```
methodunun bu class'a eklenmesi bana daha iyi olur gibi geliyor.

2024-07-18 00:34 UTC, Nbhtozcn commented on src/test/java/org/ays/tests/database/aysInstitutionName/AfetYonetimSistemi.java
> +                    "WHERE INSTITUTION.NAME = 'Afet Yönetim Sistemi'";
Bu kisim uc classta(AfetYonetimSistemi, DisasterFoundation,Voluenteer Foundation) aynen tekrar ediyor eğer yanlış anlamıyorsam, bu query'yi değişkene(INSTITUTION.NAME) bağlı olarak güncelleyip DatabaseUtility'e eklemek ve bu classlardan ilgili değişken ile cagirmak daha uygun olabilir.

2024-07-18 00:34 UTC, Nbhtozcn commented on src/test/java/org/ays/endpoints/Authorization.java
> +        adminCredentials.setSourcePage(SourcePage.INSTITUTION);
Bunun yerine:
`AdminCredentials adminCredentials = AdminCredentials.generateForAdminTwo();`

2024-07-18 12:47 UTC, Nbhtozcn approved these changes

2024-07-18 13:00 UTC, merged