AYS-420 | Refactor EmergencyEvacuationApplicationsList Response Body
afet-yonetim-sistemi/ays-be-api-automation pull request #170
Opened 2024-11-19 17:27 UTC by cagla88

## Pull Request

**Description:**
EmergencyEvacuationApplicationsList response body edited.

**Changes Made:**
`applicantFirstName`, `applicantLastName`, `applicantPhoneNumber` information has been added to the fields returned in response.
New test case added for existing not `isInPerson` application

**Additional Information:**
Add any additional information that might be relevant to reviewers.

**Reviewer Instructions:**
Provide instructions or guidelines for reviewers to follow when assessing your pull request.

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/blob/main/CONTRIBUTING.md#pull-request-naming-conventions)
      .
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/blob/main/CONTRIBUTING.md#branch-naming-conventions)
      .

- [x] **Local Testing:**
    - I have added positive and negative test scenarios (if applicable)
    - All tests are passing.
    - I tagged all test as smoke or regression
    - I added newly added tests to related xml file in test suite

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

- [x] **Reviewer Instructions:**
    - Provide instructions or guidelines for reviewers to follow when assessing your pull request.

2024-11-19 21:18 UTC, htczrrsz requested changes
Selam Çağla, 203. line ile 267. line'da ayni icerik var uyarısı alıyorum SonarLint'ten, sadece isimleri farklı gibi duruyor, bir de 251 ile 219. Sen de bir kontrol edebilir misin ?

2024-11-20 02:36 UTC, Nbhtozcn commented on src/test/java/org/ays/emergencyapplication/tests/EmergencyEvacuationApplicationsListTest.java
> +    public void testFilteringEvacuationApplicationsWithAnExistingIsInPersonApplicationData() {
method ismin "testFilteringEvacuationApplicationsByNonInPersonApplication()" seklinde olması daha anlamlı olur diye düşünüyorum.

2024-11-20 10:25 UTC, cagla88 commented
@htczrrsz selam, 203 te invalidCity testi varken 267 de invalidTargetCity testi var birbirlerinden farklı testler. Bende sonarLint te bir uyarı görünmüyor. Ek olarak bu pr ile belirttiğin testlerde bir düzenleme yapılmadı

2024-11-20 10:59 UTC, cagla88 commented on src/test/java/org/ays/emergencyapplication/tests/EmergencyEvacuationApplicationsListTest.java
> +    public void testFilteringEvacuationApplicationsWithAnExistingIsInPersonApplicationData() {
@Nbhtozcn selam method ismini güncelledim tekrar review yapabilir misiniz?

2024-11-20 13:15 UTC, agitrubard commented on src/test/java/org/ays/emergencyapplication/tests/EmergencyEvacuationApplicationsListTest.java
> +                .body("response.filteredBy.statuses[0]", equalTo("PENDING"))
Eğer varsa `EmergencyEvacuationApplicationStatus` sınıfını bu kısımlarda `"PENDING"` yerine kullanabiliriz. Eğer yoksa oluşturup yazabiliriz çünkü buradaki isimlendirmeler değiştirilmek istendiğinde ekstra efor yaratabilir

2024-11-21 05:07 UTC, agitrubard approved these changes

2024-11-21 16:20 UTC, htczrrsz approved these changes

2024-11-21 16:55 UTC, merged